apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-development
resources:
- ../../base
images:
- name: todo-app/image
  newName: aljazkovac/todo-app
  newTag: f6f79edf64e97ba95baacefb03b170092d901a21
- name: todo-backend/image
  newName: aljazkovac/todo-backend
  newTag: f6f79edf64e97ba95baacefb03b170092d901a21
- name: todo-broadcaster/image
  newName: aljazkovac/todo-broadcaster
  newTag: f6f79edf64e97ba95baacefb03b170092d901a21
